Added conditions in yml file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -52,19 +52,33 @@ jobs:
           pip install -r dev-service/requirements.txt
           pip install pytest pytest-html pytest-cov requests psycopg2-binary
       
+      # Cleanup existing container (if any)
+      - name: Cleanup existing container
+        run: docker rm -f sample_service || true
+
+      # Build service docker image
+      - name: Build Service
+        run: docker build -t sample-service ./dev-service
+
+      # Run service container
+      - name: Run container
+        run: |
+          docker run -d --name sample_service \
+            --env-file env/test.env \
+            -p 5000:5000 \
+            sample-service
+
+      # Wait for service to be ready
       - name: Wait for service
         run: |
-          for i in {1..30}; do
+          for i in {1..15}; do
             if curl -s http://localhost:5000/ping; then
               echo "Service is up"
-              exit 0
+              break
             fi
             echo "Waiting for service..."
             sleep 2
           done
-          echo "Service failed to start"
-          docker logs sample_service
-          exit 1
 
       - name: Initialize Database
         run: python dev-service/init_db.py
